export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_IDEAS_SUCCESS = "LOAD_IDEAS_SUCCESS";
export const ADD_IDEA_SUCCESS = "ADD_IDEA_SUCCESS";