export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_IDEAS_SUCCESS = "LOAD_IDEAS_SUCCESS";

export const ADD_IDEA_SUCCESS = "ADD_IDEA_SUCCESS";
export const ADD_IDEA_FAILED = "ADD_IDEA_FAILED";
export const ADD_IDEA_IN_PROGRESS = "ADD_IDEA_IN_PROGRESS";
export const ADD_IDEA_CONSUME_STATUS = "ADD_IDEA_CONSUME_STATUS";

export const UPVOTE_IDEA = "UPVOTE_IDEA";
export const UPVOTE_IDEA_SUCCESS = "UPVOTE_IDEA_SUCCESS";
export const DOWNVOTE_IDEA = "DOWNVOTE_IDEA";
export const DOWNVOTE_IDEA_SUCCESS = "DOWNVOTE_IDEA_SUCCESS";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";