export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const ADD_IDEA_SUCCESS = "ADD_IDEA_SUCCESS";
export const ADD_IDEA_FAILED = "ADD_IDEA_FAILED";
export const ADD_IDEA_IN_PROGRESS = "ADD_IDEA_IN_PROGRESS";
export const ADD_IDEA_CONSUME_STATUS = "ADD_IDEA_CONSUME_STATUS";

export const UPVOTE_IDEA = "UPVOTE_IDEA";
export const UPVOTE_IDEA_SUCCESS = "UPVOTE_IDEA_SUCCESS";
export const DOWNVOTE_IDEA = "DOWNVOTE_IDEA";
export const DOWNVOTE_IDEA_SUCCESS = "DOWNVOTE_IDEA_SUCCESS";

export const IDEA_ADDED_ON_SERVER = "IDEA_ADDED_ON_SERVER";
export const IDEA_UPDATED_ON_SERVER = "IDEA_UPDATED_ON_SERVER";
export const IDEA_REMOVED_ON_SERVER = "IDEA_REMOVED_ON_SERVER";

export const IDEAS_SYNC_STARTED = "IDEAS_SYNC_STARTED";
export const IDEAS_SYNC_COMPLETED = "IDEAS_SYNC_COMPLETED";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";